webapp/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :articles do
  	resources :comments
  end

  resources :chat_rooms, only: [:new, :create, :show, :index]

  root 'welcome#index'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

webapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

webapp/app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5 }
end

webapp/app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

webapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

webapp/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }
  
  def timestamp
  	created_at.strftime('%H:%M:%S %d %B %Y')
  end

end

webapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
  	email.split('@')[0]
  end
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

webapp/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "tramel", password: "secret", 
	except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end
	
	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

webapp/app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
	def index
		@chat_rooms = ChatRoom.all
	end

	def new
		@chat_room = ChatRoom.new
	end

	def create
		@chat_room = current_user.chat_rooms.build(chat_room_params)
		if @chat_room.save
			flash[:success] = 'Chat room added!'
			redirect_to chat_rooms_path
		else
			render 'new'
		end
	end

	def show
		@chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
		@message = Message.new
	end
	
	private

	def chat_room_params
		params.require(:chat_room).permit(:title)
	end
end

webapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "tramel", password: "secret", 
	only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

webapp/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

webapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, opts = {})
		opts[:alt] = user.name
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
					opts
	end
end

webapp/app/helpers/articles_helper.rb
module ArticlesHelper
end

webapp/app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

webapp/app/helpers/comments_helper.rb
module CommentsHelper
end

webapp/app/helpers/messages_helper.rb
module MessagesHelper
end

webapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

webapp/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

webapp/app/views/articles/edit.html.erb
<h1>Edit Forum Post</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

webapp/app/views/articles/index.html.erb
<h1>General Forum</h1>
<div class="newthread">
  <%= link_to 'New Thread', new_article_path %>
</div>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

webapp/app/views/articles/new.html.erb
<h1>New Forum Post</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

webapp/app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>
<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Back', articles_path %>

webapp/app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %> </li>

webapp/app/views/chat_rooms/index.html.erb
<h1>Chat Rooms</h1>

<p class="lead"> <%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
	<%= render @chat_rooms %>
</ul>

webapp/app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, autofocus: true, class: 'form-control' %>
	</div>

	<%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

webapp/app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
	<%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: 'form-control' %>
		<small class="text-muted">From 2 to 1000 characters</small>
	</div>

	<%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

webapp/app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>
<p>
	<%= link_to 'Destroy Comment', [comment.article, comment],
		method: :delete, data: {confirm: 'Are you sure?'} %>
</p>

webapp/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %> <br>
		<%= f.text_field :commenter %> 
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PepperSoda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<h1 class="brand_title">
    <%= link_to 'PepperSoda', controller: '/welcome' %>
  </h1>
	<div class="nav">
		<ul>
			<li>
			<%= link_to 'Home', controller: '/welcome' %>
			</li>
			<li>
			<!-- change this to forums controller soon.... -->
				<%= link_to 'Forums', controller: '/articles' %>
			</li>
			<li>
			<!-- change this to forums controller soon.... -->
				<%= link_to 'Chat', controller: '/chat_rooms' %>
			</li>
			<li>
				<%= link_to 'Products', controller: '/welcome' %>
			</li>
			<li>
				<%= link_to 'Gallery', controller: '/welcome' %>
			</li>
			<li>
				<%= link_to 'Live', controller: '/welcome' %>
			</li>
			<li>
				<%= link_to 'About', controller: '/welcome' %>
			</li>
		</ul>
	</div>
	<div class="chat">
		Chat tab
	</div>
	<div class="content">
	    <%= yield %>
  	</div>
</body>

webapp/app/views/messages/_message.html.erb
<div class="card">
	<div class="card-block">
		<div class="row">
			<div class="col-md-1">
				<%= gravatar_for message.user %>
			</div>
			<div class="col-md-11">
				<p class="card-text">
					<span class="text-muted"> <%= message.user.name %> at <%= message.timestamp %> says</span><br>
					<%= message.body %>
				</p>
			</div>
		</div>
	</div>
</div>

webapp/app/views/welcome/index.html.erb
<div class="title">
	New site!
</div>
<div class="body">
	Welcome to the new website. things are still being built. Feel free to chill and hangout in the forums or the chat room. Products coming soon! Chat coming soon! (big one for me :) ) 
	Live videos coming soon! Gallery coming soon!
</div>